# Generated by Django 4.2.1 on 2023-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('discription', models.CharField(max_length=500, verbose_name='Descrição')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Ultima alteração')),
                ('delete_on_reset_day', models.BooleanField(verbose_name='Deletar no dia de exclusão')),
            ],
        ),
    ]
