# Generated by Django 4.2.1 on 2023-06-01 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Albuns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AddField(
            model_name='album',
            name='shared_with',
            field=models.ManyToManyField(related_name='album_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com'),
        ),
    ]
