# Generated by Django 4.2.1 on 2023-06-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0004_remove_photo_album'),
        ('Albuns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(to='Photos.photo', verbose_name='Fotos'),
        ),
    ]
