# Generated by Django 4.2.1 on 2023-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0004_remove_photo_album'),
        ('Albuns', '0003_album_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='Photos.photo', verbose_name='Fotos'),
        ),
    ]
