# Generated by Django 4.2.1 on 2023-06-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Albuns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('discription', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('photo', models.ImageField(upload_to='', verbose_name='Foto')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Albuns.album', verbose_name='Album')),
            ],
        ),
    ]
